### ISSUE TITLE
Cannot open covert file to decrypt

### ISSUE THREAD

**Issue by hakavlad** [covert-encryption/covert#103]
The result:
```
$ qcovert
Traceback (most recent call last):
  File "/home/user/.local/lib/python3.9/site-packages/covert/gui/app.py", line 104, in decrypt_file
    self.decrypt(data)
  File "/home/user/.local/lib/python3.9/site-packages/covert/gui/app.py", line 109, in decrypt
    d = DecryptView(self, infile)
  File "/home/user/.local/lib/python3.9/site-packages/covert/gui/decrypt.py", line 35, in __init__
    self.decrypt_attempt()
  File "/home/user/.local/lib/python3.9/site-packages/covert/gui/decrypt.py", line 105, in decrypt_attempt
    if self.blockstream.header.key:
AttributeError: 'BlockStream' object has no attribute 'header'
```
Am I doing something wrong?

**Comment by ahnedeee** [comment]
It happened with me too, but with both formats:
- Armored
- Covert Files
