### ISSUE TITLE
neither covert nor qcovert work out of the box

### ISSUE THREAD

**Issue by clach04** [covert-encryption/covert#106]
installation setup, from checkout:

    py -3 -m venv py3venv
    py3venv\Scripts\activate.bat
    pip install -e ".[gui]"

Errors:

qcovert.exe no output, no GUI.

    (py3venv) C:\code\py\covert-encryption>python -m covert.gui
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "C:\code\py\covert-encryption\covert\gui\__main__.py", line 3, in <module>
        from covert.gui import app
      File "C:\code\py\covert-encryption\covert\gui\app.py", line 8, in <module>
        from covert.gui import res
      File "C:\code\py\covert-encryption\covert\gui\res.py", line 3, in <module>
        from covert.gui.util import datafile
      File "C:\code\py\covert-encryption\covert\gui\util.py", line 3, in <module>
        import pkg_resources
    ModuleNotFoundError: No module named 'pkg_resources'

Looks like Python 3.12 has removed pkg_resources from the standard library.

    pip install setuptools

seems to allow qconvert to then display GUI.

covert with no params help indicates, `covert edit cipher.dat` should work but appears to need a file already:

    (py3venv) C:\code\py\covert-encryption>covert edit cipher.dat
    Traceback (most recent call last):
      File "<frozen runpy>", line 198, in _run_module_as_main
      File "<frozen runpy>", line 88, in _run_code
      File "C:\code\py\covert-encryption\py3venv\Scripts\covert.exe\__main__.py", line 7, in <module>
      File "C:\code\py\covert-encryption\covert\cli\__main__.py", line 58, in main
        modes[args.mode](args)  # Normal run
        ^^^^^^^^^^^^^^^^^^^^^^
      File "C:\code\py\covert-encryption\covert\cli\edit.py", line 19, in main_edit
        with open(fname, "rb") as f:
             ^^^^^^^^^^^^^^^^^
    FileNotFoundError: [Errno 2] No such file or directory: 'cipher.dat'

Opening a single line file generated with qconvert with `covert edit cipher.dat` results in letters per line.
Also there are appear to be non-ascii characters in the tool which Windows CMD can not display:

![image](https://github.com/user-attachments/assets/9c7058bc-91dd-4f9c-903e-6ece37f93d43)

**Comment by hakavlad** [comment]
The author has not been online for 2+ years.

**Comment by clach04** [comment]
Thanks for the heads up @hakavlad , it's appreciated! Tird was actually next on my list to check out :-)

**Comment by hakavlad** [comment]
@clach04 That's why I try to make my tool not too complicated, so that I can finish it before I go offline too)
